# ESP32-P4-JC8012P4A1
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Sensor"
  room: "Your Room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome-lvgl/
    files: [guition-esp32-p4-jc8012p4a1/device/device.yaml,
            guition-esp32-p4-jc8012p4a1/device/sensors.yaml,
            guition-esp32-p4-jc8012p4a1/device/lvgl.yaml,
            guition-esp32-p4-jc8012p4a1/addon/time.yaml,
            guition-esp32-p4-jc8012p4a1/addon/backlight.yaml,
            guition-esp32-p4-jc8012p4a1/addon/network.yaml,
            guition-esp32-p4-jc8012p4a1/assets/fonts.yaml,
            guition-esp32-p4-jc8012p4a1/assets/icons.yaml,
            guition-esp32-p4-jc8012p4a1/theme/button.yaml]
    refresh: 1sec
